In [ ]:
!pip install scikit-learn
!pip install -U imbalanced-learn
!pip install scikit-learn==1.1.3

Requirement already satisfied: scikit-learn in c:\users\rishabh mishra\miniconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn) (2.2.5)
Requirement already satisfied: scipy>=1.6.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: imbalanced-learn in c:\users\rishabh mishra\miniconda3\lib\site-packages (0.13.0)
Requirement already satisfied: numpy<3,>=1.24.3 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (2.2.5)
Requirement already satisfied: scipy<2,>=1.10.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (1.15.3)
Requirement already satisfied: scikit-learn<2,>=1.3.2 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (1.6.1)
Requirement already satisfied: sklearn-compat<1,>=0.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (0.1.3)
Requirement already satisfied: joblib<2,>=1.1.1 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (1.5.1)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in c:\users\rishabh mishra\miniconda3\lib\site-packages (from imbalanced-learn) (3.6.0)

In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import csv
import os

In [80]:


# data.isnull()
# for i in range(datac.shape[0]):
#     datac.iloc[i].fillna(datac.iloc[i].mean(),inplace=True)

# datac.head()
# data.iloc[:,3:]=datac
# data.info()
# data.head()
# data['class'].unique()

In [81]:
data=pd.read_csv("hacktrain.csv")
print(data.isnull().sum())
data2=pd.read_csv("hacktest.csv")
# data.head()
# data.info()

mean_data=data.groupby('class').mean()
mean_data

# data.isnull().sum()

class_means = data.groupby('class').mean()

# Fill missing values more efficiently
for cls in data['class'].unique():
    # Get indices of rows belonging to this class
    class_mask = data['class'] == cls
    # Fill missing values with class means
    data.loc[class_mask] = data.loc[class_mask].fillna(class_means.loc[cls])



from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
data_process=data.iloc[:,3:]
data_process=pd.DataFrame(scaler.fit_transform(data_process))

drop_rows=[]
for i in range(data.shape[0]):
    for col in data_process.columns:
        if(data_process.iloc[i][col]>3 or data_process.iloc[i][col]<-3):
            drop_rows.append(i)
            break

data.drop(drop_rows,inplace=True)
data.head()
print("INFO")
data.info()

Unnamed: 0       0
ID               0
class            0
20150720_N     560
20150602_N    1200
20150517_N     800
20150501_N     960
20150415_N     480
20150330_N    1120
20150314_N     720
20150226_N    1360
20150210_N     640
20150125_N    1040
20150109_N     880
20141117_N    1280
20141101_N     400
20141016_N    1440
20140930_N     800
20140813_N     560
20140626_N    1600
20140610_N     480
20140525_N     720
20140509_N     880
20140423_N    1760
20140407_N     640
20140322_N    1120
20140218_N    1440
20140202_N     560
20140117_N    1200
20140101_N     400
dtype: int64
INFO
<class 'pandas.core.frame.DataFrame'>
Index: 7762 entries, 6 to 7999
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7762 non-null   int64
 1   ID          7762 non-null   int64
 2   class       7762 non-null   object
 3   20150720_N  7762 non-null   float64
 4   20150602_N  7762 non-null   float64
 5   20150517_N  7762 non-null   float64
 6   20150501_N  7762 non-null   float64
 7   20150415_N  7762 non-null   float64
 8   20150330_N  7762 non-null   float64
 9   20150314_N  7762 non-null   float64
 10  20150226_N  7762 non-null   float64
 11  20150210_N  7762 non-null   float64
 12  20150125_N  7762 non-null   float64
 13  20150109_N  7762 non-null   float64
 14  20141117_N  7762 non-null   float64
 15  20141101_N  7762 non-null   float64
 16  20141016_N  7762 non-null   float64
 17  20140930_N  7762 non-null   float64
 18  20140813_N  7762 non-null   float64
 19  20140626_N  7762 non-null   float64
 20  20140610_N  7762 non-null   float64
 21  20140525_N  7762 non-null   float64
 22  20140509_N  7762 non-null   float64
 23  20140423_N  7762 non-null   float64
 24  20140407_N  7762 non-null   float64
 25  20140322_N  7762 non-null   float64
 26  20140218_N  7762 non-null   float64
 27  20140202_N  7762 non-null   float64
 28  20140117_N  7762 non-null   float64
 29  20140101_N  7762 non-null   float64
dtypes: float64(27), int64(2), object(1)
memory usage: 1.8+ MB

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7762 entries, 6 to 7999
Data columns (total 30 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  7762 non-null   int64
 1   ID          7762 non-null   int64
 2   class       7762 non-null   object
 3   20150720_N  7762 non-null   float64
 4   20150602_N  7762 non-null   float64
 5   20150517_N  7762 non-null   float64
 6   20150501_N  7762 non-null   float64
 7   20150415_N  7762 non-null   float64
 8   20150330_N  7762 non-null   float64
 9   20150314_N  7762 non-null   float64
 10  20150226_N  7762 non-null   float64
 11  20150210_N  7762 non-null   float64
 12  20150125_N  7762 non-null   float64
 13  20150109_N  7762 non-null   float64
 14  20141117_N  7762 non-null   float64
 15  20141101_N  7762 non-null   float64
 16  20141016_N  7762 non-null   float64
 17  20140930_N  7762 non-null   float64
 18  20140813_N  7762 non-null   float64
 19  20140626_N  7762 non-null   float64
 20  20140610_N  7762 non-null   float64
 21  20140525_N  7762 non-null   float64
 22  20140509_N  7762 non-null   float64
 23  20140423_N  7762 non-null   float64
 24  20140407_N  7762 non-null   float64
 25  20140322_N  7762 non-null   float64
 26  20140218_N  7762 non-null   float64
 27  20140202_N  7762 non-null   float64
 28  20140117_N  7762 non-null   float64
 29  20140101_N  7762 non-null   float64
dtypes: float64(27), int64(2), object(1)
memory usage: 1.8+ MB

In [83]:
from sklearn.preprocessing import LabelEncoder
# land_cover=[sorted(['water','grass','forest','impervious','farm','grass','orchard'])]
# land_cover
enc=LabelEncoder()
data['class']=enc.fit_transform(data[['class']])
# data[data['class']==5]
# datad['class'].unique()
print("exe")

exe

C:\Users\Rishabh Mishra\miniconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [84]:
X=data.iloc[:,3:]
# X=pd.DataFrame(scaler.fit_transform(X))


y=data.iloc[:,2]
# for col in X.columns:
#     plt.figure()
#     sns.histplot(X,x=col,bins=30)
#     plt.title(f"{col}")
#     plt.show()
    
y.unique()
print("exe")
X.head()

exe

,20150720_N,20150602_N,20150517_N,20150501_N,20150415_N,20150330_N,20150314_N,20150226_N,20150210_N,20150125_N,...,20140610_N,20140525_N,20140509_N,20140423_N,20140407_N,20140322_N,20140218_N,20140202_N,20140117_N,20140101_N
6,1485.77,-223.142,727.773000,180.4910,1779.890,2613.970,1869.390,-333.333,1821.830000,-891.720,...,3192.46,2152.40,-485.563000,887.448339,178.781,1763.990000,1480.800000,931.397000,-724.129000,-1007.91000
8,2250.33,671.599,229.826000,1831.9900,1842.560,2186.740,1910.270,718.783,1499.590000,1021.580,...,1555.15,2133.41,1950.330000,1599.420000,1430.910,667.427000,1426.470000,2480.490000,1794.960000,1378.45000
9,4568.46,5011.310,3088.330000,2260.5600,1864.960,1834.980,2236.350,3938.290,1630.570000,4134.620,...,3973.62,2496.83,4758.150000,4177.900000,4663.660,2640.090000,1943.720000,4789.530000,4973.420000,206.95029
10,3417.02,-250.499,1101.121938,96.0003,574.646,215.314,865.569,378.014,1098.995648,-353.854,...,1011.93,1001.34,1217.060015,1041.890000,1406.690,2224.430000,679.548000,1427.780000,973.156134,-291.85900
11,2924.97,1365.730,575.423000,651.9700,3075.730,1181.100,1623.930,1120.460,2208.170000,-1114.860,...,1740.03,1747.02,2605.550000,1394.100000,2580.260,987.976689,880.756213,1674.185549,2548.110000,1779.79000

In [85]:
X_train=X
y_train=y
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=2)
# print(X_train)
# print(y_train)
print("exe")
print(X.shape)
print(y.shape)

exe
(7762, 27)
(7762,)

In [89]:
X_test=data2.iloc[:,2:]
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression






model=LogisticRegression(class_weight={0:10,1:1,2:10,3:10,4:10})
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
y_pred.astype(y_train.dtype)
    
        
decoding_dict = {idx: category for idx, category in enumerate(enc.classes_)}
y_class = [decoding_dict[num] for num in y_pred]
print("exe")
print(decoding_dict)
# from sklearn.metrics import f1_score
# f1=f1_score(y_test,y_pred,average='weighted')
# from sklearn.metrics import roc_auc_score
# auc=roc_auc_score(y_test,y_pred_prob,multi_class='ovr')
# print(f"F1-Score={f1}")
# print(f"ROC-Score={auc}")
# for idx,category

exe
{0: 'farm', 1: 'forest', 2: 'grass', 3: 'impervious', 4: 'orchard', 5: 'water'}

C:\Users\Rishabh Mishra\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:470: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [90]:
submission_df=pd.DataFrame({
    'ID':data2['ID'],
    'class':y_class
})
submission_df.to_csv('submission27.csv',index=False)
if os.path.exists('submission27.csv'):
    print("File saved successfully!")
    print(f"File size: {os.path.getsize('submission.csv')} bytes")
else:
    print("File not found!")
print("exe")

File saved successfully!
File size: 35977 bytes
exe